apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gkabitakis/fastify-template-server:latest
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '8080'
            - name: SERVICE
              value: 'template-server'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            periodSeconds: 60
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: template-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 8080 # port to reach Service
      targetPort: 8080 # port pointing to template-server
